-- ============================================================================
-- Migration: Create initial database schema
-- Purpose: Set up tables, indexes, triggers, and RLS policies for the AI
--          healthy meal application
-- 
-- Affected objects:
--   - Extension: pgcrypto (for UUID generation)
--   - Tables: user_profiles, recipes, recipe_variants, generation_logs
--   - Function: set_updated_at() trigger function
--   - Triggers: Auto-update timestamps on user_profiles, recipes, recipe_variants
--   - Indexes: Performance indexes for queries and text search
--   - RLS Policies: Row-level security for all tables
--
-- Notes:
--   - All tables reference auth.users(id) from Supabase Auth
--   - Soft deletes implemented via deleted_at columns
--   - Full-text search support via generated tsvector on recipes
-- ============================================================================

-- Enable UUID generation extension
-- This extension provides gen_random_uuid() function for primary keys
create extension if not exists pgcrypto;

-- ============================================================================
-- Table: user_profiles
-- Purpose: Store user profile information including dietary preferences,
--          allergens, disliked ingredients, and calorie targets
-- Relationships: One-to-one with auth.users
-- ============================================================================
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  -- Dietary preference constraint: must be one of the allowed values
  diet text check (diet in ('none','vegan','vegetarian','pescatarian','keto','paleo','halal','kosher')) default 'none',
  -- Array of allergen names (e.g., ['peanuts', 'dairy'])
  allergens text[] default '{}',
  -- Array of disliked ingredient names
  disliked_ingredients text[] default '{}',
  -- Daily calorie target, must be positive
  calorie_target int check (calorie_target > 0),
  -- Flexible JSONB field for future extensions
  extra jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- Table: recipes
-- Purpose: Store canonical user-owned recipe roots with content stored as
--          text or JSONB format
-- Relationships: Many-to-one with auth.users
-- ============================================================================
create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  -- Recipe content in plain text format
  content text,
  -- Recipe content in structured JSONB format
  content_json jsonb,
  -- Whether the recipe is publicly visible
  is_public boolean not null default false,
  -- Soft delete timestamp (null means not deleted)
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Constraint: At least one of content or content_json must be present
  constraint recipes_content_presence check (content is not null or content_json is not null)
);

-- Add generated tsvector column for full-text search
-- This column is automatically maintained and used for text search queries
alter table public.recipes
  add column if not exists content_tsv tsvector
  generated always as (
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(content, '')), 'B')
  ) stored;

-- ============================================================================
-- Table: recipe_variants
-- Purpose: Store AI-modified versions or manual variants of recipes,
--          maintaining a lineage via parent_variant_id
-- Relationships: Many-to-one with recipes, optional self-reference for lineage
-- ============================================================================
create table if not exists public.recipe_variants (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  -- Optional reference to parent variant for tracking variant lineage
  parent_variant_id uuid references public.recipe_variants(id) on delete set null,
  -- Optional reference to user who created this variant (may differ from recipe owner)
  created_by uuid references auth.users(id) on delete set null,
  -- AI model identifier if generated by AI
  model text,
  -- Prompt used to generate this variant
  prompt text,
  -- Snapshot of user preferences at time of variant generation
  preferences_snapshot jsonb,
  -- Variant content in plain text format
  output_text text,
  -- Variant content in structured JSONB format
  output_json jsonb,
  -- Soft delete timestamp (null means not deleted)
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Constraint: At least one of output_text or output_json must be present
  constraint recipe_variants_output_presence check (output_text is not null or output_json is not null)
);

-- ============================================================================
-- Table: generation_logs
-- Purpose: Audit and metrics for recipe generation activities, supporting
--          success criteria tracking and activity monitoring
-- Relationships: Many-to-one with auth.users, optional references to recipes
--                and recipe_variants
-- ============================================================================
create table if not exists public.generation_logs (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- Optional reference to recipe if log is recipe-related
  recipe_id uuid references public.recipes(id) on delete set null,
  -- Optional reference to variant if log is variant-related
  variant_id uuid references public.recipe_variants(id) on delete set null,
  -- Action type: must be one of generate, edit, or delete
  action text not null check (action in ('generate','edit','delete')),
  -- Flexible metadata JSONB for storing additional log information
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- ============================================================================
-- Function: set_updated_at()
-- Purpose: Trigger function to automatically update the updated_at timestamp
--          whenever a row is modified
-- ============================================================================
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

-- ============================================================================
-- Triggers: Auto-update timestamps
-- Purpose: Automatically set updated_at column when rows are updated
-- ============================================================================

-- Drop existing triggers if they exist (idempotent)
drop trigger if exists set_updated_at_user_profiles on public.user_profiles;
create trigger set_updated_at_user_profiles
before update on public.user_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_recipes on public.recipes;
create trigger set_updated_at_recipes
before update on public.recipes
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_recipe_variants on public.recipe_variants;
create trigger set_updated_at_recipe_variants
before update on public.recipe_variants
for each row execute function public.set_updated_at();

-- ============================================================================
-- Indexes: Performance optimization
-- Purpose: Improve query performance for common access patterns
-- ============================================================================

-- Index for user recipe listing (ownership and creation time)
-- Partial index excludes soft-deleted recipes for better performance
create index if not exists idx_recipes_user_created_at
  on public.recipes (user_id, created_at desc)
  where deleted_at is null;

-- Index for recipe variant listing by recipe
-- Partial index excludes soft-deleted variants
create index if not exists idx_recipe_variants_recipe_created_at
  on public.recipe_variants (recipe_id, created_at desc)
  where deleted_at is null;

-- Index for variant lineage traversal (parent variant lookup)
-- Partial index excludes soft-deleted variants
create index if not exists idx_recipe_variants_parent
  on public.recipe_variants (parent_variant_id)
  where deleted_at is null;

-- GIN index for full-text search on recipes
-- Partial index excludes soft-deleted recipes
create index if not exists idx_recipes_content_tsv
  on public.recipes using gin (content_tsv)
  where deleted_at is null;

-- GIN index for JSONB queries on user_profiles.extra
-- Enables efficient queries on flexible JSONB fields
create index if not exists idx_user_profiles_extra_gin
  on public.user_profiles using gin (extra);

-- GIN index for JSONB queries on recipe_variants.preferences_snapshot
-- Enables efficient filtering and querying of preference snapshots
create index if not exists idx_recipe_variants_prefs_gin
  on public.recipe_variants using gin (preferences_snapshot);

-- GIN index for JSONB queries on recipe_variants.output_json
-- Enables efficient queries on variant output data
create index if not exists idx_recipe_variants_output_gin
  on public.recipe_variants using gin ((coalesce(output_json, '{}'::jsonb)));

-- Index for activity queries (weekly counts per user)
-- Supports time-based analytics and activity tracking
create index if not exists idx_generation_logs_user_created_at
  on public.generation_logs (user_id, created_at desc);

-- Index for recipe and variant association queries
-- Supports efficient lookups of logs by recipe or variant
create index if not exists idx_generation_logs_recipe_variant
  on public.generation_logs (recipe_id, variant_id);

-- ============================================================================
-- Row Level Security (RLS): Enable on all tables
-- Purpose: Ensure all tables have RLS enabled as a security best practice
-- ============================================================================
alter table public.user_profiles enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_variants enable row level security;
alter table public.generation_logs enable row level security;

-- ============================================================================
-- RLS Policies: user_profiles
-- Purpose: Owner-only access (users can only access their own profile)
-- ============================================================================

-- Drop existing policies if they exist (idempotent)
drop policy if exists user_profiles_anon_select on public.user_profiles;
drop policy if exists user_profiles_authenticated_select on public.user_profiles;
drop policy if exists user_profiles_anon_insert on public.user_profiles;
drop policy if exists user_profiles_authenticated_insert on public.user_profiles;
drop policy if exists user_profiles_anon_update on public.user_profiles;
drop policy if exists user_profiles_authenticated_update on public.user_profiles;
drop policy if exists user_profiles_anon_delete on public.user_profiles;
drop policy if exists user_profiles_authenticated_delete on public.user_profiles;

-- Anonymous users: no access to user profiles
-- Rationale: User profiles are private and should only be accessible by the owner
create policy user_profiles_anon_select
on public.user_profiles for select
to anon
using (false);

-- Authenticated users: can select their own profile only
-- Rationale: Users need to read their own profile data
create policy user_profiles_authenticated_select
on public.user_profiles for select
to authenticated
using (user_id = auth.uid());

-- Anonymous users: can insert their own profile (for initial profile creation)
-- Rationale: Allows new users to create their profile during signup
create policy user_profiles_anon_insert
on public.user_profiles for insert
to anon
with check (user_id = auth.uid());

-- Authenticated users: can insert their own profile
-- Rationale: Allows authenticated users to create their profile if it doesn't exist
create policy user_profiles_authenticated_insert
on public.user_profiles for insert
to authenticated
with check (user_id = auth.uid());

-- Anonymous users: can update their own profile
-- Rationale: Allows profile updates during signup process
create policy user_profiles_anon_update
on public.user_profiles for update
to anon
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- Authenticated users: can update their own profile
-- Rationale: Users need to update their dietary preferences and settings
create policy user_profiles_authenticated_update
on public.user_profiles for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- Anonymous users: can delete their own profile
-- Rationale: Allows profile deletion during account cleanup
create policy user_profiles_anon_delete
on public.user_profiles for delete
to anon
using (user_id = auth.uid());

-- Authenticated users: can delete their own profile
-- Rationale: Users should be able to delete their profile data
create policy user_profiles_authenticated_delete
on public.user_profiles for delete
to authenticated
using (user_id = auth.uid());

-- ============================================================================
-- RLS Policies: recipes
-- Purpose: Owner has full access; public read when is_public = true;
--          exclude soft-deleted recipes
-- ============================================================================

-- Drop existing policies if they exist (idempotent)
drop policy if exists recipes_anon_select on public.recipes;
drop policy if exists recipes_authenticated_select on public.recipes;
drop policy if exists recipes_anon_insert on public.recipes;
drop policy if exists recipes_authenticated_insert on public.recipes;
drop policy if exists recipes_anon_update on public.recipes;
drop policy if exists recipes_authenticated_update on public.recipes;
drop policy if exists recipes_anon_delete on public.recipes;
drop policy if exists recipes_authenticated_delete on public.recipes;

-- Anonymous users: can select public, non-deleted recipes
-- Rationale: Public recipes should be discoverable by anyone
create policy recipes_anon_select
on public.recipes for select
to anon
using ((is_public = true) and deleted_at is null);

-- Authenticated users: can select their own recipes (even if not public) and public recipes
-- Rationale: Users need to see their own recipes, and public recipes are discoverable
create policy recipes_authenticated_select
on public.recipes for select
to authenticated
using (
  (user_id = auth.uid() and deleted_at is null) or
  (is_public = true and deleted_at is null)
);

-- Anonymous users: can insert recipes (will be owned by their auth.uid())
-- Rationale: Allows recipe creation during the signup/onboarding process
create policy recipes_anon_insert
on public.recipes for insert
to anon
with check (user_id = auth.uid());

-- Authenticated users: can insert their own recipes
-- Rationale: Users need to create new recipes
create policy recipes_authenticated_insert
on public.recipes for insert
to authenticated
with check (user_id = auth.uid());

-- Anonymous users: can update their own non-deleted recipes
-- Rationale: Allows recipe updates during the signup/onboarding process
create policy recipes_anon_update
on public.recipes for update
to anon
using (user_id = auth.uid() and deleted_at is null)
with check (user_id = auth.uid());

-- Authenticated users: can update their own non-deleted recipes
-- Rationale: Users need to edit their recipes
create policy recipes_authenticated_update
on public.recipes for update
to authenticated
using (user_id = auth.uid() and deleted_at is null)
with check (user_id = auth.uid());

-- Anonymous users: can delete (soft delete) their own recipes
-- Rationale: Allows recipe deletion during the signup/onboarding process
create policy recipes_anon_delete
on public.recipes for delete
to anon
using (user_id = auth.uid() and deleted_at is null);

-- Authenticated users: can delete (soft delete) their own recipes
-- Rationale: Users should be able to delete their recipes
create policy recipes_authenticated_delete
on public.recipes for delete
to authenticated
using (user_id = auth.uid() and deleted_at is null);

-- ============================================================================
-- RLS Policies: recipe_variants
-- Purpose: Allowed if user owns parent recipe; public read if parent recipe
--          is public; exclude soft-deleted variants
-- ============================================================================

-- Drop existing policies if they exist (idempotent)
drop policy if exists recipe_variants_anon_select on public.recipe_variants;
drop policy if exists recipe_variants_authenticated_select on public.recipe_variants;
drop policy if exists recipe_variants_anon_insert on public.recipe_variants;
drop policy if exists recipe_variants_authenticated_insert on public.recipe_variants;
drop policy if exists recipe_variants_anon_update on public.recipe_variants;
drop policy if exists recipe_variants_authenticated_update on public.recipe_variants;
drop policy if exists recipe_variants_anon_delete on public.recipe_variants;
drop policy if exists recipe_variants_authenticated_delete on public.recipe_variants;

-- Anonymous users: can select variants of public, non-deleted recipes if variant is not deleted
-- Rationale: Variants of public recipes should be discoverable
create policy recipe_variants_anon_select
on public.recipe_variants for select
to anon
using (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.is_public = true
      and r.deleted_at is null
  )
  and recipe_variants.deleted_at is null
);

-- Authenticated users: can select variants of their own recipes or variants of public recipes
-- Rationale: Users need to see variants of their recipes, and public recipe variants are discoverable
create policy recipe_variants_authenticated_select
on public.recipe_variants for select
to authenticated
using (
  (
    exists (
      select 1 from public.recipes r
      where r.id = recipe_variants.recipe_id
        and r.user_id = auth.uid()
        and r.deleted_at is null
    )
    and recipe_variants.deleted_at is null
  ) or (
    exists (
      select 1 from public.recipes r
      where r.id = recipe_variants.recipe_id
        and r.is_public = true
        and r.deleted_at is null
    )
    and recipe_variants.deleted_at is null
  )
);

-- Anonymous users: can insert variants for recipes they own
-- Rationale: Allows variant creation during the signup/onboarding process
create policy recipe_variants_anon_insert
on public.recipe_variants for insert
to anon
with check (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
);

-- Authenticated users: can insert variants for recipes they own
-- Rationale: Users need to create variants of their recipes
create policy recipe_variants_authenticated_insert
on public.recipe_variants for insert
to authenticated
with check (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
);

-- Anonymous users: can update variants for recipes they own (non-deleted only)
-- Rationale: Allows variant updates during the signup/onboarding process
create policy recipe_variants_anon_update
on public.recipe_variants for update
to anon
using (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
  and recipe_variants.deleted_at is null
)
with check (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
);

-- Authenticated users: can update variants for recipes they own (non-deleted only)
-- Rationale: Users need to edit their recipe variants
create policy recipe_variants_authenticated_update
on public.recipe_variants for update
to authenticated
using (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
  and recipe_variants.deleted_at is null
)
with check (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
);

-- Anonymous users: can delete (soft delete) variants for recipes they own
-- Rationale: Allows variant deletion during the signup/onboarding process
create policy recipe_variants_anon_delete
on public.recipe_variants for delete
to anon
using (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
  and recipe_variants.deleted_at is null
);

-- Authenticated users: can delete (soft delete) variants for recipes they own
-- Rationale: Users should be able to delete their recipe variants
create policy recipe_variants_authenticated_delete
on public.recipe_variants for delete
to authenticated
using (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_variants.recipe_id
      and r.user_id = auth.uid()
      and r.deleted_at is null
  )
  and recipe_variants.deleted_at is null
);

-- ============================================================================
-- RLS Policies: generation_logs
-- Purpose: Owner read and insert only; no public access
-- ============================================================================

-- Drop existing policies if they exist (idempotent)
drop policy if exists generation_logs_anon_select on public.generation_logs;
drop policy if exists generation_logs_authenticated_select on public.generation_logs;
drop policy if exists generation_logs_anon_insert on public.generation_logs;
drop policy if exists generation_logs_authenticated_insert on public.generation_logs;
drop policy if exists generation_logs_anon_update on public.generation_logs;
drop policy if exists generation_logs_authenticated_update on public.generation_logs;
drop policy if exists generation_logs_anon_delete on public.generation_logs;
drop policy if exists generation_logs_authenticated_delete on public.generation_logs;

-- Anonymous users: no select access to generation logs
-- Rationale: Generation logs are private audit data, should only be visible to the owner
create policy generation_logs_anon_select
on public.generation_logs for select
to anon
using (false);

-- Authenticated users: can select their own generation logs
-- Rationale: Users need to view their own activity logs for metrics and analytics
create policy generation_logs_authenticated_select
on public.generation_logs for select
to authenticated
using (user_id = auth.uid());

-- Anonymous users: can insert their own generation logs
-- Rationale: Allows logging activity during the signup/onboarding process
create policy generation_logs_anon_insert
on public.generation_logs for insert
to anon
with check (user_id = auth.uid());

-- Authenticated users: can insert their own generation logs
-- Rationale: System needs to log user activities for metrics and analytics
create policy generation_logs_authenticated_insert
on public.generation_logs for insert
to authenticated
with check (user_id = auth.uid());

-- Anonymous users: no update access to generation logs
-- Rationale: Logs are immutable audit records and should not be modified
create policy generation_logs_anon_update
on public.generation_logs for update
to anon
using (false);

-- Authenticated users: no update access to generation logs
-- Rationale: Logs are immutable audit records and should not be modified
create policy generation_logs_authenticated_update
on public.generation_logs for update
to authenticated
using (false);

-- Anonymous users: no delete access to generation logs
-- Rationale: Logs are audit records and should not be deleted to maintain data integrity
create policy generation_logs_anon_delete
on public.generation_logs for delete
to anon
using (false);

-- Authenticated users: no delete access to generation logs
-- Rationale: Logs are audit records and should not be deleted to maintain data integrity
create policy generation_logs_authenticated_delete
on public.generation_logs for delete
to authenticated
using (false);

